# Generated by Django 3.2.5 on 2021-07-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='employers',
        ),
    ]
