# Generated by Django 3.2.5 on 2021-07-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20210716_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='hr_employers',
        ),
    ]
